"""temp_migration

Revision ID: 1394057ea1e6
Revises: e9a47c0be35b
Create Date: 2026-01-15 15:38:22.798388

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1394057ea1e6"
down_revision: Union[str, None] = "e9a47c0be35b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_items")
    op.drop_table("payments")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('payments_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "SUCCESSFUL", "CANCELLED", "REFUNDED", name="paymentstatusenum"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "amount",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "external_payment_id",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name="payments_order_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="payments_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="payments_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "payment_items",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("payment_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("order_item_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "price_at_payment",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
            name=op.f("payment_items_order_item_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"], ["payments.id"], name=op.f("payment_items_payment_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("payment_items_pkey")),
    )
    # ### end Alembic commands ###
