[mypy]
python_version = 3.12
explicit_package_bases = True
ignore_missing_imports = True
check_untyped_defs = False
disable_error_code = attr-defined, assignment, arg-type, call-arg
files = src/**/*.py
