name: CI Pipeline

on:
  pull_request:
    branches: ["main"]

jobs:
  lint-and-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run Linters
        run: |
          poetry run flake8 src
          poetry run black --check src
      - name: Run Mypy
        run: |
          cd src
          poetry run mypy .

  integration-tests:
    needs: lint-and-types
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-file: [
          "test_accounts.py",
          "test_movies.py",
          "test_profiles.py",
          "test_cart.py",
          "test_orders.py",
          "test_payments.py"
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Run Integration Tests in Docker
        env:
          SECRET_KEY_ACCESS: ${{ secrets.SECRET_KEY_ACCESS }}
          SECRET_KEY_REFRESH: ${{ secrets.SECRET_KEY_REFRESH }}
        run: |
          docker compose -f docker-compose-tests.yml run --rm web pytest tests/test_integration/${{ matrix.test-file }}

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose-tests.yml down

  test-e2e:
    needs: lint-and-types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Docker Tests
        env:
          SECRET_KEY_ACCESS: ${{ secrets.SECRET_KEY_ACCESS }}
          SECRET_KEY_REFRESH: ${{ secrets.SECRET_KEY_REFRESH }}
        run: docker compose -f docker-compose-tests.yml run --rm --build web pytest
      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose-tests.yml down